### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by PowerPress** [kaonashi-passwords/Kaonashi#2]
On page 16 of your slide deck what URL was that service you were using? Do you happen to have an English version of the deck perhaps? Awesome presentation and thanks for making this available.

**Comment by pcaro90** [comment]
The web application you can see on page 16 is our tool, Kaonashi. We did a demo at RootedCON 2019, which will be accesible at YouTube soon (in Spanish, I'm afraid!). However, we haven't released it to the public.

There is no English version of the presentation, I'm sorry!

**Comment by PowerPress** [comment]
Thank you for sharing this awesome presentation. Hope to see kaonashi get released eventually looks awesome.
